In [9]:
import requests
from bs4 import BeautifulSoup
import pandas as pd   

base_url = "https://books.toscrape.com/catalogue/page-{}.html"

all_items = []

for i in range(1, 51):
    print(f"Scraping page {i}")  

    url = base_url.format(i)
    res = requests.get(url)

    soup = BeautifulSoup(res.text, "html.parser")

    articles = soup.select("article.product_pod")

    for article in articles:
        title = article.find("h3").find("a")["title"]
        price = article.select_one(".price_color").text.split("£")[1]
        rating = article.select_one(".star-rating")["class"][1]

        all_items.append([title, price, rating])


df = pd.DataFrame(all_items, columns=["TITLE", "PRICE", "RATING"])

df.head()

Scraping page 1
Scraping page 2
Scraping page 3
Scraping page 4
Scraping page 5
Scraping page 6
Scraping page 7
Scraping page 8
Scraping page 9
Scraping page 10
Scraping page 11
Scraping page 12
Scraping page 13
Scraping page 14
Scraping page 15
Scraping page 16
Scraping page 17
Scraping page 18
Scraping page 19
Scraping page 20
Scraping page 21
Scraping page 22
Scraping page 23
Scraping page 24
Scraping page 25
Scraping page 26
Scraping page 27
Scraping page 28
Scraping page 29
Scraping page 30
Scraping page 31
Scraping page 32
Scraping page 33
Scraping page 34
Scraping page 35
Scraping page 36
Scraping page 37
Scraping page 38
Scraping page 39
Scraping page 40
Scraping page 41
Scraping page 42
Scraping page 43
Scraping page 44
Scraping page 45
Scraping page 46
Scraping page 47
Scraping page 48
Scraping page 49
Scraping page 50

                                   TITLE  PRICE RATING
0                   A Light in the Attic  51.77  Three
1                     Tipping the Velvet  53.74    One
2                             Soumission  50.10    One
3                          Sharp Objects  47.82   Four
4  Sapiens: A Brief History of Humankind  54.23   Five

In [10]:
df

                                                 TITLE  PRICE RATING
0                                 A Light in the Attic  51.77  Three
1                                   Tipping the Velvet  53.74    One
2                                           Soumission  50.10    One
3                                        Sharp Objects  47.82   Four
4                Sapiens: A Brief History of Humankind  54.23   Five
..                                                 ...    ...    ...
995  Alice in Wonderland (Alice's Adventures in Won...  55.53    One
996   Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)  57.06   Four
997  A Spy's Devotion (The Regency Spies of London #1)  16.97   Five
998                1st to Die (Women's Murder Club #1)  53.98    One
999                 1,000 Places to See Before You Die  26.08   Five

[1000 rows x 3 columns]

In [11]:
print(len(all_items))

1000